# Site settings
title: Intrinsic Ratio Generator
description: > # Intrinsic ratio generator and calculator for building
  responsive blocks. Commonly used for HTML5 videos and complex layouts.
baseurl: "/instrinsic-ratio-generator/" # the subpath of your site, e.g. /blog/
url: "http://aeb.sr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
